import type { Project } from "@/types";

export const PROJECTS: Project[] = [
  {
    id: "1",
    title: "Platform Manajemen Terpusat Body-Worn Camera (BWC)",
    description: `Platform komprehensif dan terpusat yang dirancang untuk pengelolaan dan pemantauan Body-Worn Camera (BWC) yang mulus. Sistem ini mengatur seluruh siklus operasional, termasuk inventaris perangkat, data personel, logika penugasan, dan konfigurasi geofencing. Kemampuan utamanya meliputi pemantauan streaming video real-time dan autentikasi terpusat yang aman melalui OAuth 2.0. Fitur unggulannya adalah "AI Query," yang memberdayakan pengguna untuk menanyakan dataset kompleks menggunakan bahasa alami, secara drastis menyederhanakan pengambilan dan analisis data.`,
    thumbnail: "/images/no-image.png",
    technologies: [
      "Vue.js",
      "Express.js",
      "PostgreSQL",
      "OAuth 2.0",
      "AI Query",
      "Minio",
      "Docker",
      "Git",
      "Turborepo",
    ],
    links: {
      demo: undefined,
      github: undefined,
      website: undefined,
    },
    slug: "bwc-platform",
    period: {
      start: "2024-01-01",
      end: "2024-12-31",
    },
    images: [
      "/images/no-image.png",
      "/images/no-image.png",
      "/images/no-image.png",
    ],
  },
  {
    id: "2",
    title: "Sistem Monitoring Kualitas Air Limbah Berbasis IoT (SPARING)",
    description: `Solusi IoT canggih yang dirancang untuk memantau kualitas air limbah sesuai dengan regulasi KLHK (SPARING). Diterapkan di berbagai Water Treatment Plant (WTP), sistem ini memiliki arsitektur aplikasi ganda: backend Node-RED untuk akuisisi dan transmisi data yang kuat ke server KLHK, dan dasbor HMI berbasis Flutter yang memberikan visualisasi dan kontrol real-time kepada operator langsung di lokasi pabrik.`,
    thumbnail: "/images/no-image.png",
    technologies: [
      "Vue.js",
      "Express.js",
      "PostgreSQL",
      "OAuth 2.0",
      "AI Query",
      "Minio",
      "Docker",
      "Git",
      "Turborepo",
    ],
    links: {
      demo: undefined,
      github: undefined,
    },
    slug: "sparing-iot-monitoring",
    period: {
      start: "2024-01-01",
      end: "2024-12-31",
    },
    images: [
      "/images/no-image.png",
      "/images/no-image.png",
      "/images/no-image.png",
    ],
  },
  {
    id: "3",
    title: "Ekosistem Manajemen Smartwatch IoT End-to-End",
    description: `Platform IoT end-to-end untuk pelacakan dan manajemen smartwatch, yang diarsiteki sebagai monorepo yang dapat diskalakan menggunakan Turborepo. Ekosistem ini terdiri dari empat layanan integral: server TCP berkinerja tinggi untuk ingest data real-time tingkat rendah, REST API Node.js yang tangguh, dasbor frontend Vue.js yang responsif, dan penjadwal pelaporan otomatis. Kontribusi utama meliputi perancangan arsitektur sistem, pengembangan lapisan komunikasi TCP tingkat rendah, dan optimalisasi alur kerja monorepo.`,
    thumbnail: "/images/no-image.png",
    technologies: ["Vue.js", "Express.js", "Node.js", "TypeScript", "API Integration", "Charts"],
    links: {
      demo: undefined,
      github: undefined,
    },
    slug: "smartwatch-iot",
    period: {
      start: "2024-01-01",
      end: "2024-12-31",
    },
    images: [
      "/images/no-image.png",
      "/images/no-image.png",
      "/images/no-image.png",
    ],
  },
  {
    id: "4",
    title: "Operasional IT & Manajemen Infrastruktur - Pusat Informasi Kriminal Nasional",
    description: `Memimpin operasional IT harian dan stabilitas infrastruktur untuk Pusat Informasi Kriminal Nasional. Tanggung jawab mencakup pemantauan kesehatan server secara proaktif, pemeliharaan sistem rutin, dan eksekusi protokol pemulihan bencana yang ketat untuk memastikan ketersediaan tinggi 24/7. Berfokus pada menjaga uptime sistem, integritas data.`,
    thumbnail: "/images/no-image.png",
    technologies: ["Vue.js", "Express.js", "Node.js", "TypeScript", "API Integration", "Charts"],
    links: {
      demo: undefined,
      github: undefined,
    },
    slug: "it-ops-pikn",
    period: {
      start: "2024-01-01",
      end: "2024-12-31",
    },
    images: [
      "/images/no-image.png",
      "/images/no-image.png",
      "/images/no-image.png",
    ],
  },
  {
    id: "5",
    title: "Sistem Informasi Manajemen SimKPLP - Kementerian Perhubungan",
    description: `Berkontribusi pada pengembangan inti aplikasi SimKPLP (Laravel), dengan fokus pada perluasan fitur, optimalisasi kinerja, dan pemeliharaan kode. Berkolaborasi dalam tim agile untuk mengirimkan modul fungsional tertentu, melakukan refactoring kode lama, mengoptimalkan kueri database, dan menyelesaikan bug kritis, memastikan sistem yang tangguh dan stabil untuk Kementerian Perhubungan.`,
    thumbnail: "/images/no-image.png",
    technologies: ["Vue.js", "Express.js", "Node.js", "TypeScript", "API Integration", "Charts"],
    links: {
      demo: undefined,
      github: undefined,
    },
    slug: "simkplp",
    period: {
      start: "2024-01-01",
      end: "2024-12-31",
    },
    images: [
      "/images/no-image.png",
      "/images/no-image.png",
      "/images/no-image.png",
    ],
  },
  {
    id: "6",
    title: "Sistem Manajemen Ruang Rapat Terintegrasi",
    description: `Mengembangkan solusi manajemen ruang rapat holistik yang menampilkan aplikasi web full-stack Next.js sebagai pusat kontrol utama dan penyedia API. Sistem ini terintegrasi dengan aplikasi tampilan ruangan berbasis Flutter, yang disinkronkan secara real-time melalui WebSocket yang di-host dalam lingkungan Next.js. Ini memastikan penjadwalan yang mulus, pembaruan status instan, dan pemanfaatan ruang yang efisien di seluruh organisasi.`,
    thumbnail: "/images/no-image.png",
    technologies: ["Vue.js", "Express.js", "Node.js", "TypeScript", "API Integration", "Charts"],
    links: {
      demo: undefined,
      github: undefined,
    },
    slug: "meeting-room-management",
    period: {
      start: "2024-01-01",
      end: "2024-12-31",
    },
    images: [
      "/images/no-image.png",
      "/images/no-image.png",
      "/images/no-image.png",
    ],
  },
  {
    id: "7",
    title: "Aplikasi Mobile Simpusaka - LPSK",
    description: `Merekayasa aplikasi mobile Simpusaka (Flutter) untuk LPSK, yang berfungsi sebagai gerbang digital aman bagi warga untuk meminta perlindungan saksi dan korban. Aplikasi ini menampilkan alur kerja permohonan multi-tahap, unggahan dokumen yang aman, dan autentikasi biometrik. Hasil utama meliputi UI/UX yang berpusat pada pengguna, pesan terenkripsi untuk komunikasi rahasia, dan penerapan protokol keamanan berlapis untuk melindungi data sensitif.`,
    thumbnail: "/images/no-image.png",
    technologies: ["Vue.js", "Express.js", "Node.js", "TypeScript", "API Integration", "Charts"],
    links: {
      demo: undefined,
      github: undefined,
    },
    slug: "simpusaka-lpsk",
    period: {
      start: "2024-01-01",
      end: "2024-12-31",
    },
    images: [
      "/images/no-image.png",
      "/images/no-image.png",
      "/images/no-image.png",
    ],
  },
  {
    id: "8",
    title: "Website Profil Resmi LPSK",
    description: `Memimpin siklus pengembangan penuh website resmi LPSK, menghadirkan platform modern, responsif, dan dioptimalkan untuk SEO menggunakan Next.js. Proyek ini mencakup CMS yang dibangun khusus untuk memberdayakan staf non-teknis dengan manajemen konten mandiri. Memprioritaskan kinerja tinggi melalui Static Site Generation (SSG) dan meningkatkan keterlibatan pengguna dengan animasi dinamis dan antarmuka yang dipoles serta mudah diakses.`,
    thumbnail: "/images/no-image.png",
    technologies: ["Vue.js", "Express.js", "Node.js", "TypeScript", "API Integration", "Charts"],
    links: {
      demo: "https://www.lpsk.go.id/beranda",
      github: undefined,
    },
    slug: "website-profil-lpsk",
    period: {
      start: "2024-01-01",
      end: "2024-12-31",
    },
    images: [
      "/images/no-image.png",
      "/images/no-image.png",
      "/images/no-image.png",
    ],
  },
  {
    id: "9",
    title: "Website Profil & Portofolio Perusahaan",
    description: `Merancang dan mengembangkan website profil perusahaan berkinerja tinggi menggunakan Next.js, menampilkan animasi canggih dan tata letak yang sepenuhnya responsif. Membangun CMS khusus dengan REST API untuk memfasilitasi pembaruan konten yang mudah. Proyek ini memanfaatkan tumpukan teknologi modern termasuk TypeScript, Tailwind CSS, dan Framer Motion untuk memberikan pengalaman pengguna premium yang ramah SEO dengan waktu muat yang cepat.`,
    thumbnail: "/images/no-image.png",
    technologies: ["Vue.js", "Express.js", "Node.js", "TypeScript", "API Integration", "Charts"],
    links: {
      demo: undefined,
      github: undefined,
    },
    slug: "website-profil-perusahaan",
    period: {
      start: "2024-01-01",
      end: "2024-12-31",
    },
    images: [
      "/images/no-image.png",
      "/images/no-image.png",
      "/images/no-image.png",
    ],
  },
  {
    id: "10",
    title: "Sistem E-Persuratan (Surat Elektronik)",
    description: `Mengembangkan sistem E-Persuratan yang komprehensif menggunakan arsitektur decoupled dengan frontend SPA Angular dan backend REST API Nest.js. Mengelola siklus pengembangan penuh, mulai dari desain API dan logika alur kerja disposisi yang kompleks hingga implementasi antarmuka pengguna yang responsif. Fitur utama meliputi integrasi tanda tangan digital (TTE), kontrol akses berbasis peran, dan basis kode modular yang aman secara tipe.`,
    thumbnail: "/images/no-image.png",
    technologies: ["Vue.js", "Express.js", "Node.js", "TypeScript", "API Integration", "Charts"],
    links: {
      demo: undefined,
      github: undefined,
    },
    slug: "e-persuratan",
    period: {
      start: "2024-01-01",
      end: "2024-12-31",
    },
    images: [
      "/images/no-image.png",
      "/images/no-image.png",
      "/images/no-image.png",
    ],
  },
  {
    id: "11",
    title: "Aplikasi Wayfinder Interaktif",
    description: `Membangun aplikasi wayfinding interaktif dari awal menggunakan arsitektur full-stack Next.js. Aplikasi ini menyediakan pemosisian pengguna real-time, peta interaktif, dan perhitungan rute optimal ke outlet tujuan menggunakan algoritma A*/Dijkstra yang diimplementasikan melalui API Routes. Termasuk panel admin komprehensif untuk mengelola data peta dan lokasi outlet, memberikan pengalaman navigasi yang mulus.`,
    thumbnail: "/images/no-image.png",
    technologies: ["Vue.js", "Express.js", "Node.js", "TypeScript", "API Integration", "Charts"],
    links: {
      demo: undefined,
      github: undefined,
    },
    slug: "wayfinder",
    period: {
      start: "2024-01-01",
      end: "2024-12-31",
    },
    images: [
      "/images/no-image.png",
      "/images/no-image.png",
      "/images/no-image.png",
    ],
  },
  {
    id: "12",
    title: "Ekosistem Superapp & Backoffice Bawaslu",
    description: `Bertindak sebagai Frontend Developer utama untuk dua platform penting: Superapp Android berbasis Flutter untuk pelaporan publik dan koordinasi petugas lapangan, serta dasbor Backoffice berbasis Angular untuk administrasi data terpusat. Tanggung jawab meliputi penerjemahan desain menjadi UI/UX yang responsif, integrasi REST API yang kompleks, implementasi fitur perangkat seperti GPS dan Kamera, serta visualisasi dataset besar untuk pemantauan pemilu skala nasional.`,
    thumbnail: "/images/no-image.png",
    technologies: ["Vue.js", "Express.js", "Node.js", "TypeScript", "API Integration", "Charts"],
    links: {
      demo: undefined,
      github: undefined,
    },
    slug: "superapp-backoffice-bawaslu",
    period: {
      start: "2024-01-01",
      end: "2024-12-31",
    },
    images: [
      "/images/no-image.png",
      "/images/no-image.png",
      "/images/no-image.png",
    ],
  },
];
