import type { TechStack } from "@/types";
import {
  Code2Icon,
  FileCodeIcon,
  BoxIcon,
  PaletteIcon,
  DatabaseIcon,
  GitBranchIcon,
  ContainerIcon,
} from "lucide-react";

export const techStackData: TechStack[] = [
  {
    id: "1",
    name: "React",
    icon: Code2Icon,
    category: "Frontend",
    level: "expert",
    yearsOfExperience: 3,
    projectCount: 15,
    description:
      "Library JavaScript untuk membangun user interface yang interaktif",
  },
  {
    id: "2",
    name: "Next.js",
    icon: FileCodeIcon,
    category: "Frontend",
    level: "expert",
    yearsOfExperience: 2,
    projectCount: 10,
    description: "Framework React untuk production dengan SSR dan SSG",
  },
  {
    id: "3",
    name: "TypeScript",
    icon: Code2Icon,
    category: "Frontend",
    level: "advanced",
    yearsOfExperience: 3,
    projectCount: 18,
    description: "Superset JavaScript dengan static typing",
  },
  {
    id: "4",
    name: "Node.js",
    icon: BoxIcon,
    category: "Backend",
    level: "expert",
    yearsOfExperience: 3,
    projectCount: 12,
    description: "Runtime JavaScript untuk backend development",
  },
  {
    id: "5",
    name: "Tailwind CSS",
    icon: PaletteIcon,
    category: "Frontend",
    level: "expert",
    yearsOfExperience: 2,
    projectCount: 15,
    description: "Utility-first CSS framework untuk styling modern",
  },
  {
    id: "6",
    name: "PostgreSQL",
    icon: DatabaseIcon,
    category: "Database",
    level: "advanced",
    yearsOfExperience: 2,
    projectCount: 8,
    description: "Relational database management system",
  },
  {
    id: "7",
    name: "Git",
    icon: GitBranchIcon,
    category: "DevOps",
    level: "expert",
    yearsOfExperience: 3,
    projectCount: 20,
    description: "Version control system untuk kolaborasi tim",
  },
  {
    id: "8",
    name: "Docker",
    icon: ContainerIcon,
    category: "DevOps",
    level: "intermediate",
    yearsOfExperience: 1,
    projectCount: 5,
    description: "Platform containerization untuk deployment",
  },
];
