import type { WorkExperience } from "@/types";

export const workExperienceData: WorkExperience[] = [
  {
    id: "1",
    company: "PT. Sahabat Teknologi Sejahtera",
    role: "Fullstack Developer",
    startDate: "2025-01",
    endDate: null,
    description: `Bertanggung jawab penuh atas seluruh siklus pengembangan produk IoT (Internet of Things), mulai dari tahap inisiasi dan perancangan arsitektur sistem hingga implementasi full-stack (Frontend & Backend) dan deployment. Fokus utama meliputi perancangan antarmuka pengguna (UI/UX) yang intuitif, pengembangan backend yang berkinerja tinggi untuk pemrosesan data real-time, serta memastikan skalabilitas dan keandalan integrasi antara perangkat keras dan platform cloud.`,
    technologies: [
      "Express.js",
      "Vue.js",
      "Golang",
      "Flutter",
      "PostgreSQL",
      "RabbitMQ",
      "Node-RED",
      "Redis",
      "Minio",
      "Docker",
      "Git",
      "VPS",
    ],
    location: "Tangerang, Indonesia",
  },
  {
    id: "2",
    company: "CV. Mareca Yasa Media",
    role: "Fullstack Developer",
    startDate: "2022-01",
    endDate: "2024-12",
    description: `Mengelola end-to-end development untuk beragam solusi digital, termasuk aplikasi web berskala enterprise, website profil korporat, dan aplikasi mobile. Bertanggung jawab mulai dari analisis kebutuhan klien, perancangan sistem, coding, hingga pemeliharaan pasca-peluncuran. Berhasil mengantarkan proyek-proyek yang meningkatkan efisiensi operasional klien dan memperkuat kehadiran digital mereka melalui penerapan teknologi modern dan praktik terbaik rekayasa perangkat lunak.`,
    technologies: [
      "Express.js",
      "Next.js",
      "Golang",
      "Flutter",
      "Angular",
      "Nest.js",
      "PostgreSQL",
      "Minio",
      "Docker",
      "Git",
      "VPS",
    ],
    location: "Bandung, Indonesia",
  },
];
