import type { WorkExperience } from "@/types";

export const workExperienceData: WorkExperience[] = [
  {
    id: "1",
    company: "PT. Sahabat Teknologi Sejahtera",
    role: "Fullstack Developer",
    startDate: "2025-01",
    endDate: null,
    description: `Memegang tanggung jawab penuh atas siklus hidup pengembangan produk IoT. Tanggung jawab saya dimulai dari fase desain (konseptualisasi, UI/UX, arsitektur data) hingga melakukan eksekusi pengembangan full-stack (Frontend & Backend). Saya bertanggung jawab untuk memastikan produk akhir tidak hanya fungsional tetapi juga andal dan scalable untuk integrasi perangkat di lapangan.`,
    technologies: [
      "Express.js",
      "Vue.js",
      "Golang",
      "Flutter",
      "PostgreSQL",
      "RabbitMQ",
      "Node-RED",
      "Redis",
      "Minio",
      "Docker",
      "Git",
      "VPS",
    ],
    location: "Tangerang, Indonesia",
  },
  {
    id: "2",
    company: "CV. Mareca yasa Media",
    role: "Fullstack Developer",
    startDate: "2022-01",
    endDate: "2024-12",
    description: `Saya bertanggung jawab penuh atas seluruh siklus hidup pengembangan perangkat lunak, mulai dari tahap perencanaan dan desain hingga deployment dan pemeliharaan. Saya bekerja secara langsung dengan tim dan klien untuk membangun berbagai solusi digital, termasuk aplikasi web, website profil, dan aplikasi mobile, yang dapat menjawab kebutuhan bisnis mereka secara efektif.`,
    technologies: [
      "Express.js",
      "Next.js",
      "Golang",
      "Flutter",
      "Angular",
      "Nest.js",
      "PostgreSQL",
      "Minio",
      "Docker",
      "Git",
      "VPS",
    ],
    location: "Bandung, Indonesia",
  },
];
